Atividade 1
deboramsol/DVNube-Bootcamp-1---Exerc-cios pull request #1
Opened 2023-02-13 18:00 UTC by deboramsol

Atividade 1 - Pseudocódigo

2023-02-13 19:43 UTC, dvnube requested changes
seria algo mais na pegada:

levantar do sofá
caminhar até o banheiro
se porta fechada então
    abrir porta
fim se
entrar no banheiro
pegar escova de dente
pegar pasta de dente
se pasta de dente fechada então
    abrir pasta de dente
fim se
.
.
.

2023-02-13 21:47 UTC, deboramsol commented
@dvnube atualização feita da atividade.

2023-02-14 00:19 UTC, dvnube requested changes

2023-02-14 00:19 UTC, dvnube commented on Atividade1.txt
> +Fechar torneira
já que vc utilizou a função `abrirTorneira()` , crie a função `fecharTorneira()`

2023-02-14 00:19 UTC, dvnube commented on Atividade1.txt
> +Secar boca e mãos na toalha
se a sua intenção é secar, ao mesmo tempo, bocas e mãos, ok
mas se vc pensou em "secar a boca e depois as mãos", favor dividir em duas ações difernetes
- secar a boca na toalha
- secar a mão na toalha

2023-02-14 11:51 UTC, deboramsol commented
@dvnube segue o pseudocódigo com as devidas alterações.

2023-02-14 12:43 UTC, deboramsol commented
@dvnube realizada as devidas alterações. Espero q esteja tudo correto.

2023-02-14 13:51 UTC, dvnube approved these changes
adicionei pequenos reviews, mas tá show , é isso
faz as alterações, mas tá aprovado

2023-02-14 13:51 UTC, dvnube commented on Atividade1.txt
> +    entrar no banheiro
perceba que `entrar no banheiro` é uma ação comum
o que vc fez não está errado
mas vc poderia ter escrito menos:
```
Se (porta banheiro fechada) entao
    abrir  porta
fimse
entrar no banheiro
```

2023-02-14 13:51 UTC, dvnube commented on Atividade1.txt
> +    Escovar os dentes
`tempo = tempo + 1 segundo`

2023-02-14 13:51 UTC, dvnube commented on Atividade1.txt
> +fimfecharTorneura
erro de compilação (digitação)
`fimFecharTorneira`

2023-02-14 14:05 UTC, deboramsol commented on Atividade1.txt
> +fimfecharTorneura
Alterações feitas. Obrigada.

2023-03-01 02:11 UTC, merged